import { GithubIcon } from "./ui/GithubIcon";
import { Tooltip, TooltipContent, TooltipTrigger } from "./ui/tooltip";

export const LayoutFooter: React.FC = () => {
  return (
    <footer className="flex flex-col lg:flex-row gap-1 bg-gray-200 text-xs p-2 text-center">
      <div className="flex-grow">
        Copyright &copy; Drew Maughan, all rights reserved. Derived from a
        project generated by{" "}
        <a className="underline" href="https://lovable.dev" target="_blank">
          Lovable
        </a>
        .
      </div>

      <Tooltip>
        <TooltipTrigger asChild>
          <a className="flex-shrink-0" href="https://github.com/legendarydrew">
            <GithubIcon />
          </a>
        </TooltipTrigger>
        <TooltipContent sideOffset={1}>legendarydrew on Github</TooltipContent>
      </Tooltip>
    </footer>
  );
};
