export const LayoutFooter: React.FC = () => {
    return (
        <footer className="bg-gray-200 text-xs p-2 text-center">
            Copyright &copy; Drew Maughan, all rights reserved.
            Derived from a project generated by{" "}
            <a className="underline" href="https://lovable.dev" target="_blank">
                Lovable
            </a>.
        </footer>
    );
};
